name: MyPy Action
description: Run tox [testenv:type] and create annotations on PR with errors.
author: 'Artem Sereda'
branding:
  icon: check-circle
  color: yellow
inputs:
  check_name:
    description: The name of the check to add annotations to. Generally the same as the job that uses this action
    required: true
  command:
    description: MyPy command to run
    default: tox run
  env_name:
    description: Name of tox env to execute
    default: type
  args:
    description: Positional argument to pass to mypy

runs:
  using: node16
  main: dist/index.js